version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/geospatial:latest
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - run:
          command: |
            R install_texlive.R
            R -e 'devtools::install_github("hughparsonage/grattanReporter")'
            R -e 'library(grattanReporter);checkGrattanReport(compile = TRUE)'
            
