version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/tidyverse
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - run:
          command: |
            Rscript -e 'devtools::install_github("hughparsonage/grattanReporter", ref = "tinytex-compatible")'
            ls
            file ./travis/travis.sh
            source ./travis/travis.sh
            tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
            tlmgr update --all
            sudo apt-get update
            sudo apt-get install texlive-bibtex-extra
            wget http://mirrors.ctan.org/biblio/biber/binaries/Linux/biber-linux_x86_64.tar.gz
            tar xzf biber-linux_x86_64.tar.gz
            export PATH=$PATH:$PWD
            tlmgr update biber
            Rscript -e 'hutils::provide.dir("travis/grattanReport")'
            Rscript -e 'print(Sys.which("pdflatex"))'
            Rscript -e 'print(Sys.which("latexmk"))'
            Rscript -e 'library(grattanReporter);checkGrattanReport(compile = TRUE, pre_release = TRUE)'


            
