version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/geospatial:latest
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - run:
          command: |
            R -e "devtools::install_github('hughparsonage/TeXCheckR')"
            R -e "devtools::install_github('hughparsonage/grattanReporter')"
