version: 2
jobs:
  build:
    docker:
      - image: sumdoc/texlive-2018
    steps:
      - checkout
      - run:
          command: |
            Rscript -e 'install.packages(c("devtools", "TeXCheckR"))'
            Rscript -e 'devtools::install_github("hughparsonage/grattanReporter")'
            Rscript -e 'library(grattanReporter);checkGrattanReport(compile = TRUE, pre_release = TRUE)'
          
