version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/tidyverse
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - run:
          command: |
            Rscript -e 'devtools::install_github("hughparsonage/grattanReporter")'
            Rscript -e 'devtools::install_github('yihui/tinytex');library(tinytex);pdflatex("Report.tex")'
            Rscript -e 'hutils::provide.dir("travis/grattanReport")'
            Rscript -e 'library(grattanReporter);checkGrattanReport(compile = TRUE, pre_release = TRUE)'
            
