version: 2
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: rocker/geospatial:latest
        environment:
          NOT_CRAN: true
    steps:
      - checkout
      - run:
          command: |
            R -e 'devtools::install_github("hughparsonage/grattanReporter")'
            R -e 'devtools::install_github(c("yihui/tinytex"), quiet = TRUE)'
            R -e 'tryCatch(tinytex::install_tinytex(), error = function(e) tinytex::pdflatex("Report.tex"))'
            R -e 'hutils::provide.dir("travis/grattanReport")'
            R -e 'library(grattanReporter);checkGrattanReport(compile = TRUE)'
            
